apiVersion: v1
data:
  app-config.properties: |
    # 数据库地址
    postgres_host=pg-quant-invest
    postgres_port=5432
    postgres_user=user
    postgres_password=password
    postgres_database=market

    log_level=DEBUG
    log_output_path=/app/data/log/bsery-app.log
    data_folder=/app/data/cache/
    trade_rate=2.5
    ticker_x=510300
    ticker_y=159915
    strategy_status_cd=R    
kind: ConfigMap
metadata:
  name: bsery-main-config
  namespace: classic-dev
