apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    image.openshift.io/triggers: "null"
  name: systest-bsery
  namespace: classic-dev
spec:
  parallelism: 1    
  completions: 1    
  backoffLimit: 1
  activeDeadlineSeconds: 1800
  template:         
    metadata:
      name: bsery
    spec:
      containers:
        - name: bsery
          image: image-registry.openshift-image-registry.svc:5000/classic-dev/bsery:latest
          command: ["bsery"]
          env:
          - name: TZ
            value: Asia/Shanghai
          resources:
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/resources/app-config.properties
              subPath: app-config.properties
              readOnly: false
              name: bsery-properties-volume
      volumes:
        - configMap:
            name: bsery-main-config
            defaultMode: 272
            optional: false
          name: bsery-properties-volume
      restartPolicy: Never 
